# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sudoku_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(528, 613)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.howto_label = QtWidgets.QLabel(self.centralwidget)
        self.howto_label.setObjectName("howto_label")
        self.verticalLayout.addWidget(self.howto_label)
        self.sudoku_layout = QtWidgets.QGridLayout()
        self.sudoku_layout.setHorizontalSpacing(1)
        self.sudoku_layout.setVerticalSpacing(12)
        self.sudoku_layout.setObjectName("sudoku_layout")
        self.sudoku_box31 = QtWidgets.QGridLayout()
        self.sudoku_box31.setSpacing(0)
        self.sudoku_box31.setObjectName("sudoku_box31")
        self.cell31_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell31_11.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell31_11.setFont(font)
        self.cell31_11.setObjectName("cell31_11")
        self.sudoku_box31.addWidget(self.cell31_11, 0, 0, 1, 1)
        self.cell31_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell31_12.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell31_12.setFont(font)
        self.cell31_12.setObjectName("cell31_12")
        self.sudoku_box31.addWidget(self.cell31_12, 0, 1, 1, 1)
        self.cell31_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell31_21.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell31_21.setFont(font)
        self.cell31_21.setObjectName("cell31_21")
        self.sudoku_box31.addWidget(self.cell31_21, 1, 0, 1, 1)
        self.cell31_31 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell31_31.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell31_31.setFont(font)
        self.cell31_31.setObjectName("cell31_31")
        self.sudoku_box31.addWidget(self.cell31_31, 2, 0, 1, 1)
        self.cell31_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell31_13.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell31_13.setFont(font)
        self.cell31_13.setObjectName("cell31_13")
        self.sudoku_box31.addWidget(self.cell31_13, 0, 2, 1, 1)
        self.cell31_22 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell31_22.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell31_22.setFont(font)
        self.cell31_22.setObjectName("cell31_22")
        self.sudoku_box31.addWidget(self.cell31_22, 1, 1, 1, 1)
        self.cell31_23 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell31_23.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell31_23.setFont(font)
        self.cell31_23.setObjectName("cell31_23")
        self.sudoku_box31.addWidget(self.cell31_23, 1, 2, 1, 1)
        self.cell31_32 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell31_32.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell31_32.setFont(font)
        self.cell31_32.setObjectName("cell31_32")
        self.sudoku_box31.addWidget(self.cell31_32, 2, 1, 1, 1)
        self.cell31_33 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell31_33.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell31_33.setFont(font)
        self.cell31_33.setObjectName("cell31_33")
        self.sudoku_box31.addWidget(self.cell31_33, 2, 2, 1, 1)
        self.sudoku_layout.addLayout(self.sudoku_box31, 2, 0, 1, 1)
        self.sudoku_box21 = QtWidgets.QGridLayout()
        self.sudoku_box21.setSpacing(0)
        self.sudoku_box21.setObjectName("sudoku_box21")
        self.cell21_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell21_11.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell21_11.setFont(font)
        self.cell21_11.setObjectName("cell21_11")
        self.sudoku_box21.addWidget(self.cell21_11, 0, 0, 1, 1)
        self.cell21_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell21_21.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell21_21.setFont(font)
        self.cell21_21.setObjectName("cell21_21")
        self.sudoku_box21.addWidget(self.cell21_21, 1, 0, 1, 1)
        self.cell21_31 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell21_31.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell21_31.setFont(font)
        self.cell21_31.setObjectName("cell21_31")
        self.sudoku_box21.addWidget(self.cell21_31, 2, 0, 1, 1)
        self.cell21_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell21_12.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell21_12.setFont(font)
        self.cell21_12.setObjectName("cell21_12")
        self.sudoku_box21.addWidget(self.cell21_12, 0, 1, 1, 1)
        self.cell21_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell21_13.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell21_13.setFont(font)
        self.cell21_13.setObjectName("cell21_13")
        self.sudoku_box21.addWidget(self.cell21_13, 0, 2, 1, 1)
        self.cell21_22 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell21_22.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell21_22.setFont(font)
        self.cell21_22.setObjectName("cell21_22")
        self.sudoku_box21.addWidget(self.cell21_22, 1, 1, 1, 1)
        self.cell21_23 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell21_23.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell21_23.setFont(font)
        self.cell21_23.setObjectName("cell21_23")
        self.sudoku_box21.addWidget(self.cell21_23, 1, 2, 1, 1)
        self.cell21_32 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell21_32.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell21_32.setFont(font)
        self.cell21_32.setObjectName("cell21_32")
        self.sudoku_box21.addWidget(self.cell21_32, 2, 1, 1, 1)
        self.cell21_33 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell21_33.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell21_33.setFont(font)
        self.cell21_33.setObjectName("cell21_33")
        self.sudoku_box21.addWidget(self.cell21_33, 2, 2, 1, 1)
        self.sudoku_layout.addLayout(self.sudoku_box21, 1, 0, 1, 1)
        self.sudoku_box12 = QtWidgets.QGridLayout()
        self.sudoku_box12.setSpacing(0)
        self.sudoku_box12.setObjectName("sudoku_box12")
        self.cell12_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell12_11.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell12_11.setFont(font)
        self.cell12_11.setObjectName("cell12_11")
        self.sudoku_box12.addWidget(self.cell12_11, 0, 0, 1, 1)
        self.cell12_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell12_21.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell12_21.setFont(font)
        self.cell12_21.setObjectName("cell12_21")
        self.sudoku_box12.addWidget(self.cell12_21, 1, 0, 1, 1)
        self.cell12_31 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell12_31.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell12_31.setFont(font)
        self.cell12_31.setObjectName("cell12_31")
        self.sudoku_box12.addWidget(self.cell12_31, 2, 0, 1, 1)
        self.cell12_22 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell12_22.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell12_22.setFont(font)
        self.cell12_22.setObjectName("cell12_22")
        self.sudoku_box12.addWidget(self.cell12_22, 1, 1, 1, 1)
        self.cell12_23 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell12_23.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell12_23.setFont(font)
        self.cell12_23.setObjectName("cell12_23")
        self.sudoku_box12.addWidget(self.cell12_23, 1, 2, 1, 1)
        self.cell12_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell12_12.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell12_12.setFont(font)
        self.cell12_12.setObjectName("cell12_12")
        self.sudoku_box12.addWidget(self.cell12_12, 0, 1, 1, 1)
        self.cell12_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell12_13.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell12_13.setFont(font)
        self.cell12_13.setObjectName("cell12_13")
        self.sudoku_box12.addWidget(self.cell12_13, 0, 2, 1, 1)
        self.cell12_32 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell12_32.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell12_32.setFont(font)
        self.cell12_32.setObjectName("cell12_32")
        self.sudoku_box12.addWidget(self.cell12_32, 2, 1, 1, 1)
        self.cell12_33 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell12_33.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell12_33.setFont(font)
        self.cell12_33.setObjectName("cell12_33")
        self.sudoku_box12.addWidget(self.cell12_33, 2, 2, 1, 1)
        self.sudoku_layout.addLayout(self.sudoku_box12, 0, 1, 1, 1)
        self.sudoku_box11 = QtWidgets.QGridLayout()
        self.sudoku_box11.setSpacing(0)
        self.sudoku_box11.setObjectName("sudoku_box11")
        self.cell11_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell11_13.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell11_13.setFont(font)
        self.cell11_13.setObjectName("cell11_13")
        self.sudoku_box11.addWidget(self.cell11_13, 0, 2, 1, 1)
        self.cell11_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell11_21.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell11_21.setFont(font)
        self.cell11_21.setObjectName("cell11_21")
        self.sudoku_box11.addWidget(self.cell11_21, 1, 0, 1, 1)
        self.cell11_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell11_12.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell11_12.setFont(font)
        self.cell11_12.setObjectName("cell11_12")
        self.sudoku_box11.addWidget(self.cell11_12, 0, 1, 1, 1)
        self.cell11_11 = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell11_11.sizePolicy().hasHeightForWidth())
        self.cell11_11.setSizePolicy(sizePolicy)
        self.cell11_11.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell11_11.setFont(font)
        self.cell11_11.setObjectName("cell11_11")
        self.sudoku_box11.addWidget(self.cell11_11, 0, 0, 1, 1)
        self.cell11_31 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell11_31.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell11_31.setFont(font)
        self.cell11_31.setObjectName("cell11_31")
        self.sudoku_box11.addWidget(self.cell11_31, 2, 0, 1, 1)
        self.cell11_22 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell11_22.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell11_22.setFont(font)
        self.cell11_22.setObjectName("cell11_22")
        self.sudoku_box11.addWidget(self.cell11_22, 1, 1, 1, 1)
        self.cell11_32 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell11_32.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell11_32.setFont(font)
        self.cell11_32.setObjectName("cell11_32")
        self.sudoku_box11.addWidget(self.cell11_32, 2, 1, 1, 1)
        self.cell11_23 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell11_23.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell11_23.setFont(font)
        self.cell11_23.setObjectName("cell11_23")
        self.sudoku_box11.addWidget(self.cell11_23, 1, 2, 1, 1)
        self.cell11_33 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell11_33.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell11_33.setFont(font)
        self.cell11_33.setObjectName("cell11_33")
        self.sudoku_box11.addWidget(self.cell11_33, 2, 2, 1, 1)
        self.sudoku_layout.addLayout(self.sudoku_box11, 0, 0, 1, 1)
        self.sudoku_box22 = QtWidgets.QGridLayout()
        self.sudoku_box22.setSpacing(0)
        self.sudoku_box22.setObjectName("sudoku_box22")
        self.cell22_31 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell22_31.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell22_31.setFont(font)
        self.cell22_31.setObjectName("cell22_31")
        self.sudoku_box22.addWidget(self.cell22_31, 2, 0, 1, 1)
        self.cell22_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell22_21.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell22_21.setFont(font)
        self.cell22_21.setObjectName("cell22_21")
        self.sudoku_box22.addWidget(self.cell22_21, 1, 0, 1, 1)
        self.cell22_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell22_11.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell22_11.setFont(font)
        self.cell22_11.setObjectName("cell22_11")
        self.sudoku_box22.addWidget(self.cell22_11, 0, 0, 1, 1)
        self.cell22_22 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell22_22.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell22_22.setFont(font)
        self.cell22_22.setObjectName("cell22_22")
        self.sudoku_box22.addWidget(self.cell22_22, 1, 1, 1, 1)
        self.cell22_23 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell22_23.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell22_23.setFont(font)
        self.cell22_23.setObjectName("cell22_23")
        self.sudoku_box22.addWidget(self.cell22_23, 1, 2, 1, 1)
        self.cell22_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell22_12.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell22_12.setFont(font)
        self.cell22_12.setObjectName("cell22_12")
        self.sudoku_box22.addWidget(self.cell22_12, 0, 1, 1, 1)
        self.cell22_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell22_13.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell22_13.setFont(font)
        self.cell22_13.setObjectName("cell22_13")
        self.sudoku_box22.addWidget(self.cell22_13, 0, 2, 1, 1)
        self.cell22_32 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell22_32.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell22_32.setFont(font)
        self.cell22_32.setObjectName("cell22_32")
        self.sudoku_box22.addWidget(self.cell22_32, 2, 1, 1, 1)
        self.cell22_33 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell22_33.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell22_33.setFont(font)
        self.cell22_33.setObjectName("cell22_33")
        self.sudoku_box22.addWidget(self.cell22_33, 2, 2, 1, 1)
        self.sudoku_layout.addLayout(self.sudoku_box22, 1, 1, 1, 1)
        self.sudoku_box23 = QtWidgets.QGridLayout()
        self.sudoku_box23.setSpacing(0)
        self.sudoku_box23.setObjectName("sudoku_box23")
        self.cell23_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell23_21.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell23_21.setFont(font)
        self.cell23_21.setObjectName("cell23_21")
        self.sudoku_box23.addWidget(self.cell23_21, 1, 0, 1, 1)
        self.cell23_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell23_11.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell23_11.setFont(font)
        self.cell23_11.setObjectName("cell23_11")
        self.sudoku_box23.addWidget(self.cell23_11, 0, 0, 1, 1)
        self.cell23_31 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell23_31.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell23_31.setFont(font)
        self.cell23_31.setObjectName("cell23_31")
        self.sudoku_box23.addWidget(self.cell23_31, 2, 0, 1, 1)
        self.cell23_22 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell23_22.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell23_22.setFont(font)
        self.cell23_22.setObjectName("cell23_22")
        self.sudoku_box23.addWidget(self.cell23_22, 1, 1, 1, 1)
        self.cell23_23 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell23_23.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell23_23.setFont(font)
        self.cell23_23.setObjectName("cell23_23")
        self.sudoku_box23.addWidget(self.cell23_23, 1, 2, 1, 1)
        self.cell23_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell23_12.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell23_12.setFont(font)
        self.cell23_12.setObjectName("cell23_12")
        self.sudoku_box23.addWidget(self.cell23_12, 0, 1, 1, 1)
        self.cell23_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell23_13.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell23_13.setFont(font)
        self.cell23_13.setObjectName("cell23_13")
        self.sudoku_box23.addWidget(self.cell23_13, 0, 2, 1, 1)
        self.cell23_32 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell23_32.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell23_32.setFont(font)
        self.cell23_32.setObjectName("cell23_32")
        self.sudoku_box23.addWidget(self.cell23_32, 2, 1, 1, 1)
        self.cell23_33 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell23_33.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell23_33.setFont(font)
        self.cell23_33.setObjectName("cell23_33")
        self.sudoku_box23.addWidget(self.cell23_33, 2, 2, 1, 1)
        self.sudoku_layout.addLayout(self.sudoku_box23, 1, 2, 1, 1)
        self.sudoku_box32 = QtWidgets.QGridLayout()
        self.sudoku_box32.setSpacing(0)
        self.sudoku_box32.setObjectName("sudoku_box32")
        self.cell32_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell32_11.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell32_11.setFont(font)
        self.cell32_11.setObjectName("cell32_11")
        self.sudoku_box32.addWidget(self.cell32_11, 0, 0, 1, 1)
        self.cell32_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell32_12.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell32_12.setFont(font)
        self.cell32_12.setObjectName("cell32_12")
        self.sudoku_box32.addWidget(self.cell32_12, 0, 1, 1, 1)
        self.cell32_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell32_21.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell32_21.setFont(font)
        self.cell32_21.setObjectName("cell32_21")
        self.sudoku_box32.addWidget(self.cell32_21, 1, 0, 1, 1)
        self.cell32_31 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell32_31.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell32_31.setFont(font)
        self.cell32_31.setObjectName("cell32_31")
        self.sudoku_box32.addWidget(self.cell32_31, 2, 0, 1, 1)
        self.cell32_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell32_13.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell32_13.setFont(font)
        self.cell32_13.setObjectName("cell32_13")
        self.sudoku_box32.addWidget(self.cell32_13, 0, 2, 1, 1)
        self.cell32_22 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell32_22.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell32_22.setFont(font)
        self.cell32_22.setObjectName("cell32_22")
        self.sudoku_box32.addWidget(self.cell32_22, 1, 1, 1, 1)
        self.cell32_32 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell32_32.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell32_32.setFont(font)
        self.cell32_32.setObjectName("cell32_32")
        self.sudoku_box32.addWidget(self.cell32_32, 2, 1, 1, 1)
        self.cell32_23 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell32_23.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell32_23.setFont(font)
        self.cell32_23.setObjectName("cell32_23")
        self.sudoku_box32.addWidget(self.cell32_23, 1, 2, 1, 1)
        self.cell32_33 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell32_33.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell32_33.setFont(font)
        self.cell32_33.setObjectName("cell32_33")
        self.sudoku_box32.addWidget(self.cell32_33, 2, 2, 1, 1)
        self.sudoku_layout.addLayout(self.sudoku_box32, 2, 1, 1, 1)
        self.sudoku_box13 = QtWidgets.QGridLayout()
        self.sudoku_box13.setSpacing(0)
        self.sudoku_box13.setObjectName("sudoku_box13")
        self.cell13_22 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell13_22.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell13_22.setFont(font)
        self.cell13_22.setObjectName("cell13_22")
        self.sudoku_box13.addWidget(self.cell13_22, 1, 1, 1, 1)
        self.cell13_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell13_11.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell13_11.setFont(font)
        self.cell13_11.setObjectName("cell13_11")
        self.sudoku_box13.addWidget(self.cell13_11, 0, 0, 1, 1)
        self.cell13_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell13_12.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell13_12.setFont(font)
        self.cell13_12.setObjectName("cell13_12")
        self.sudoku_box13.addWidget(self.cell13_12, 0, 1, 1, 1)
        self.cell13_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell13_13.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell13_13.setFont(font)
        self.cell13_13.setObjectName("cell13_13")
        self.sudoku_box13.addWidget(self.cell13_13, 0, 2, 1, 1)
        self.cell13_32 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell13_32.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell13_32.setFont(font)
        self.cell13_32.setObjectName("cell13_32")
        self.sudoku_box13.addWidget(self.cell13_32, 2, 1, 1, 1)
        self.cell13_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell13_21.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell13_21.setFont(font)
        self.cell13_21.setObjectName("cell13_21")
        self.sudoku_box13.addWidget(self.cell13_21, 1, 0, 1, 1)
        self.cell13_31 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell13_31.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell13_31.setFont(font)
        self.cell13_31.setObjectName("cell13_31")
        self.sudoku_box13.addWidget(self.cell13_31, 2, 0, 1, 1)
        self.cell13_23 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell13_23.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell13_23.setFont(font)
        self.cell13_23.setObjectName("cell13_23")
        self.sudoku_box13.addWidget(self.cell13_23, 1, 2, 1, 1)
        self.cell13_33 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell13_33.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell13_33.setFont(font)
        self.cell13_33.setObjectName("cell13_33")
        self.sudoku_box13.addWidget(self.cell13_33, 2, 2, 1, 1)
        self.sudoku_layout.addLayout(self.sudoku_box13, 0, 2, 1, 1)
        self.sudoku_box33 = QtWidgets.QGridLayout()
        self.sudoku_box33.setSpacing(0)
        self.sudoku_box33.setObjectName("sudoku_box33")
        self.cell33_33 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell33_33.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell33_33.setFont(font)
        self.cell33_33.setObjectName("cell33_33")
        self.sudoku_box33.addWidget(self.cell33_33, 2, 2, 1, 1)
        self.cell33_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell33_21.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell33_21.setFont(font)
        self.cell33_21.setObjectName("cell33_21")
        self.sudoku_box33.addWidget(self.cell33_21, 1, 0, 1, 1)
        self.cell33_31 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell33_31.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell33_31.setFont(font)
        self.cell33_31.setObjectName("cell33_31")
        self.sudoku_box33.addWidget(self.cell33_31, 2, 0, 1, 1)
        self.cell33_32 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell33_32.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell33_32.setFont(font)
        self.cell33_32.setObjectName("cell33_32")
        self.sudoku_box33.addWidget(self.cell33_32, 2, 1, 1, 1)
        self.cell33_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell33_11.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell33_11.setFont(font)
        self.cell33_11.setObjectName("cell33_11")
        self.sudoku_box33.addWidget(self.cell33_11, 0, 0, 1, 1)
        self.cell33_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell33_12.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell33_12.setFont(font)
        self.cell33_12.setObjectName("cell33_12")
        self.sudoku_box33.addWidget(self.cell33_12, 0, 1, 1, 1)
        self.cell33_22 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell33_22.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell33_22.setFont(font)
        self.cell33_22.setObjectName("cell33_22")
        self.sudoku_box33.addWidget(self.cell33_22, 1, 1, 1, 1)
        self.cell33_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell33_13.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell33_13.setFont(font)
        self.cell33_13.setObjectName("cell33_13")
        self.sudoku_box33.addWidget(self.cell33_13, 0, 2, 1, 1)
        self.cell33_23 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell33_23.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cell33_23.setFont(font)
        self.cell33_23.setObjectName("cell33_23")
        self.sudoku_box33.addWidget(self.cell33_23, 1, 2, 1, 1)
        self.sudoku_layout.addLayout(self.sudoku_box33, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.sudoku_layout)
        self.solve_btn = QtWidgets.QPushButton(self.centralwidget)
        self.solve_btn.setObjectName("solve_btn")
        self.verticalLayout.addWidget(self.solve_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 528, 26))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.sudoku_yukle_action = QtWidgets.QAction(MainWindow)
        self.sudoku_yukle_action.setObjectName("sudoku_yukle_action")
        self.sudokuyu_kaydet_action = QtWidgets.QAction(MainWindow)
        self.sudokuyu_kaydet_action.setObjectName("sudokuyu_kaydet_action")
        self.yeni_sudoku_action = QtWidgets.QAction(MainWindow)
        self.yeni_sudoku_action.setObjectName("yeni_sudoku_action")
        self.menuDosya.addAction(self.yeni_sudoku_action)
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.sudoku_yukle_action)
        self.menuDosya.addAction(self.sudokuyu_kaydet_action)
        self.menubar.addAction(self.menuDosya.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sudoku Çözücü"))
        self.howto_label.setText(_translate("MainWindow", "Bildiğiniz değerleri ilgili kutulara giriniz. Bilmediğiniz değerleri boş bırakınız veya 0 giriniz."))
        self.cell31_11.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell31_12.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell31_21.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell31_31.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell31_13.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell31_22.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell31_23.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell31_32.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell31_33.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell21_11.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell21_21.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell21_31.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell21_12.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell21_13.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell21_22.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell21_23.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell21_32.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell21_33.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell12_11.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell12_21.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell12_31.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell12_22.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell12_23.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell12_12.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell12_13.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell12_32.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell12_33.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell11_13.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell11_21.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell11_12.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell11_11.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell11_31.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell11_22.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell11_32.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell11_23.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell11_33.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell22_31.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell22_21.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell22_11.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell22_22.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell22_23.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell22_12.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell22_13.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell22_32.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell22_33.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell23_21.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell23_11.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell23_31.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell23_22.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell23_23.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell23_12.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell23_13.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell23_32.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell23_33.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell32_11.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell32_12.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell32_21.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell32_31.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell32_13.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell32_22.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell32_32.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell32_23.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell32_33.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell13_22.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell13_11.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell13_12.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell13_13.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell13_32.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell13_21.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell13_31.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell13_23.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell13_33.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell33_33.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell33_21.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell33_31.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell33_32.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell33_11.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell33_12.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell33_22.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell33_13.setPlaceholderText(_translate("MainWindow", "0"))
        self.cell33_23.setPlaceholderText(_translate("MainWindow", "0"))
        self.solve_btn.setText(_translate("MainWindow", "ÇÖZ"))
        self.menuDosya.setTitle(_translate("MainWindow", "Dosya"))
        self.sudoku_yukle_action.setText(_translate("MainWindow", "Sudoku Yükle"))
        self.sudokuyu_kaydet_action.setText(_translate("MainWindow", "Sudokuyu Kaydet"))
        self.yeni_sudoku_action.setText(_translate("MainWindow", "Yeni Sudoku"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

